# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        invoice:
            local:
                directory: '%kernel.project_dir%/var/storage/invoice'

    filesystems:
        invoice:
            adapter: invoice
            alias: League\Flysystem\Filesystem
