webpack_encore:
    output_path: false

    # if using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'

    # preload all rendered script and link tags automatically via the http2 Link header
    # preload: true

    # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    # strict_mode: false

    builds:
        shop: '%kernel.project_dir%/public/assets/shop'
        admin: '%kernel.project_dir%/public/assets/admin'
        vaaCharTheme: '%kernel.project_dir%/public/assets/vaachar-theme'

    # Cache the entrypoints.json (rebuild Symfony's cache when entrypoints.json changes)
    # Put in config/packages/prod/webpack_encore.yaml
    # cache: true
