version: '3.4'

services:
    php:
        image: vaachar/sylius_php:latest
        depends_on:
            - mysql
        restart: unless-stopped
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=${DATABASE_URL}
            - MAILER_URL=${MAILER_URL}
            - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./.env:/srv/sylius/.env:ro
            - ./var:/srv/sylius/var:rw,delegated
            - ./public/media:/srv/sylius/public/media:rw,delegated

    enqueue_consumer:
        image: vaachar/sylius_php:latest
        depends_on:
            - mysql
            - php
        restart: unless-stopped
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=${DATABASE_URL}
            - ENQUEUE_CONSUMER=true
            - MAILER_URL=${MAILER_URL}
            - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./.env:/srv/sylius/.env:ro
            - ./var:/srv/sylius/var:rw,delegated
            - ./public/media:/srv/sylius/public/media:rw,delegated
        command: ["bin/console", "enqueue:consume", "--setup-broker", "-vvv"]

    mysql:
        image: percona:5.7
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./docker/mysql/data:/var/lib/mysql:rw,delegated

    nginx:
        image: vaachar/sylius_nginx:latest
        depends_on:
            - php
        restart: unless-stopped
        volumes:
            - ./public/media:/srv/sylius/public/media:ro,delegated
        ports:
            - "80:80"

    elasticsearch:
        image: vaachar/sylius_elasticsearch:latest
        restart: unless-stopped
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data:rw
        environment:
            - node.name=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "xpack.security.enabled=false"
        ulimits:
            memlock:
                soft: -1
                hard: -1

volumes:
    elasticsearch-data:
