version: '3.4'

services:
    php:
        image: vaachar/sylius_php:${TAG_VERSION:-latest}
        build:
            context: .
            target: sylius_php

    enqueue_consumer:
        build:
            context: .
            target: sylius_php

    nodejs:
        image: vaachar/sylius_nodejs:${TAG_VERSION:-latest}
        build:
            context: .
            target: sylius_nodejs
        depends_on:
            - php
        environment:
            - PHP_HOST=php
            - PHP_PORT=9000
        volumes:
            - .:/srv/sylius:rw,cached
        ports:
            - "35729:35729"

    nginx:
        image: vaachar/sylius_nginx:${TAG_VERSION:-latest}
        build:
            context: .
            target: sylius_nginx
        depends_on:
            - php
            - nodejs

    elasticsearch:
        image: vaachar/sylius_elasticsearch:${TAG_VERSION:-latest}
        build:
            context: .
            target: sylius_elasticsearch

    redis:
        image: vaachar/sylius_redis:${TAG_VERSION:-latest}
        build:
            context: .
            target: sylius_redis
