odiseo_sylius_banner_plugin_admin:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/admin.yaml"
    prefix: "/%sylius_admin.path_name%"

odiseo_sylius_banner_plugin_shop:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}/banners
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

odiseo_sylius_banner_plugin_api:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/api.yaml"
    prefix: /api
