bitbag_sylius_cms_plugin:
    resource: "@BitBagSyliusCmsPlugin/Resources/config/routing.yml"

bitbag_sylius_mollie_plugin:
    resource: "@BitBagSyliusMolliePlugin/Resources/config/routing.yaml"

bitbag_sylius_product_bundle_plugin:
    resource: "@BitBagSyliusProductBundlePlugin/Resources/config/routing.yml"

vaachar_sylius_shipping_information_page_plugin:
    resource: "@VaaCharSyliusShippingInformationPagePlugin/Resources/config/routing.yml"

monsieurbiz_search_plugin:
    resource: "@MonsieurBizSyliusSearchPlugin/Resources/config/routing.yaml"

mango_sylius_order_comments_plugin:
    resource: "@MangoSyliusOrderCommentsPlugin/Resources/config/routing.yml"
    prefix: /admin

odiseo_sylius_banner_plugin_admin:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/admin.yaml"
    prefix: /admin

odiseo_sylius_banner_plugin_shop:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}/banners
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$

odiseo_sylius_banner_plugin_api:
    resource: "@OdiseoSyliusBannerPlugin/Resources/config/routing/api.yaml"
    prefix: /api
